name: Build nightly SNAPSHOT

on:
  workflow_dispatch:
  schedule:
    # Midnight every day
    - cron: "0 0 * * *"
  push:
    # Rerun if workflow changes
    branches:
      - 'master'
    paths:
      - '**/snapshot.yml'

jobs:
  gradle:
    if: github.repository_owner == 'gurkenlabs'
    name: Publish nightly snapshot
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Publish
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          NEXUS_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        with:
          arguments: |
            prepareVote
            -Prc=1
            -Pgh
            -Prelease=false
            -PskipJavadoc
            -PskipSpotless
            -PghGitSourceUsername=gurkenlabs
            -PghGitSourcePassword=$GITHUB_TOKEN
            -PghNexusUsername=$NEXUS_USERNAME
            -PghNexusPassword=$NEXUS_PASSWORD
            -PuseInMemoryKey=true
            -Psigning.inMemoryKey=$GPG_SIGNING_KEY
            -Psigning.password=$GPG_PASSPHRASE
